language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
notifications:
  email: false
cache:
  directories:
    - node_modules
# allow headful tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - 'if [ "$NODE7" = "true" ]; then npm run lint; fi'
  - 'if [ "$NODE7" = "true" ]; then npm run coverage; fi'
  - 'if [ "$NODE7" = "true" ]; then npm run test-doclint; fi'
  - 'if [ "$NODE6" = "true" ]; then npm run unit-node6; fi'
jobs:
  include:
    - node_js: "7.10.1"
      env: NODE7=true
    - node_js: "6.12.3"
      env: NODE6=true
before_deploy: "npm run apply-next-version"
deploy:
  provider: npm
  email: aslushnikov@gmail.com
  api_key:
    secure: Hpm5uE47cDeHd3uAYwyzCvDH6a1ihgHjniZeulrLUKMmqofbjT2ophtgiJzuH7Y0QFDRbKInHna7VsJia68GPPlc1MfUphUvWOHtsvS2yES8uN3sA0/bWx9o3t8kaBIENquDV3NcHZDTHRMMwOBKWbPm01kv+w7pM3VxzQ8uQsBcIQfG3248EBoJSVg940EiQFi4nZyam++Ens0jgcr/Ysz2bBd4MxlT6GdEacsXfbzq4iRvKRnf0rvJwcNdmwq2drKQutIDeJo/m9Ge8/CvbLVyWvN7C8o5DH7UrRlZeAZrXkEr93PujYv8UvmOmglzUzdJXyyi4uc4bLIuzZqun7oxP9+v9SFu8X5Waxvwv8WVp9cOK/JT/9GZvL6aGJ3zVgWombj9AZMbDeNoFl4YLqlUbPT+rAzYdLHIXkNgprG78E/9h0H4PAbObTggA9+4OOs+18c6QYLzsxUo7FkHMyt5h3MjhUHJrd/kr3+RYaM+hUBAataeRgWB9G2LHe6HTHiKKlNLUQ2oJHXOwhGEWFy0gJmJEKG0295c3lDiykSvq6aMj1g7s2hfWdhVvRFO0oV6djIIktiezmUOZxc7roo2aW+P6RJVxjVk0jKf4Fnyx2itdLLXdn4xvpyrf5XU7+KgLJW5zsHsTTzAmzjOv0gv6Y27ZwE03H+U+HmbufQ=
  on:
    branch: master
    condition: "$NODE7 = true"
  skip_cleanup: true
  tag: next
